In [24]:
import numpy as np

#x = np.array([
#    [1, 2, 3],
#    [4, 5, 6],
#    [7, 8, 9]
#])


def return_zeros(array):
	return np.zeros_like(array)
    
#print(return_zeros(x))

M = np.zeros((16, 16))
#M[::4, :] = 1

def sample_every_4th_row(A):
	A[::4, :] = 0.25
	return A


def create_random_matrix(x, step, seed=None):
    """
    Create a mask that samples every 'stride'-th column.

    Parameters:
    - x: (n,m) matrix
    - stride: how often to keep a column (e.g., 4 keeps every 4th)

    Returns:
    - mask: binary mask with 0s in sampled columns
    """
    
    if seed is not None:
        np.random.seed(seed)
    
    rows, cols = x.shape
    masked_matrix = np.copy(x)
    
    for j in range(1, cols, step):
        masked_matrix[:, j] = 0
    	
    return masked_matrix
    
x3 = np.ones((8,8), dtype=int)
#x4 = np.random.rand(2,2)
#print(x4)
print('------------------------')
print(x3)
print('------------------------')
#matrix = create_random_matrix((16,16))

#print(matrix.shape)
#print(matrix[:, 0])
print(create_random_matrix(x3, 4))
print('----------------------')
#print(x4 @ create_column_mask(x4, 2))

------------------------
[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
------------------------
[[1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]
 [1 0 1 1 1 0 1 1]]
----------------------
